"""Export a VRGDG scene's image-to-video render as a standalone ComfyUI workflow.

    python scripts/export_i2v_workflow.py --project BurningManGirl --scene 2
    python scripts/export_i2v_workflow.py --project BurningManGirl --scene 2 --width 960 --height 544 --no-upscale

The Builder drives LTX through `/vrgdg/workflow_runner/build_i2v_prompt` and then
waits. When a render hangs - as scene 2 did, deadlocked in the latent upscale for
2.5 hours holding 60 GB - you get an error message and no way to inspect or adjust
anything. This writes the *same graph* to a file you can open in ComfyUI, so the
knobs are in front of you.

It is the same route the Builder uses, so it is not a reconstruction. What this
adds is filling in every model name and sampler setting from
`GET /vrgdg/music_builder/model_defaults` - the shipped template carries the pack
author's filenames and leaves the loaders empty unless the payload supplies
yours, which is the documented "template model names are not yours" trap.

ComfyUI 0.32 with frontend 1.48 opens API-format JSON directly (Workflow > Open,
or drag onto the canvas). Node positions are generated by the frontend, so the
layout will be mechanical - the graph is correct, it just will not be pretty.

**The knobs**, by node id, printed again at the end of every export:

    width / height        two PrimitiveInt nodes feeding the latent
    pass-1 sigmas         ManualSigmas, 9 values = 8 steps, the base render
    pass-2 sigmas         ManualSigmas, 4 values = 3 steps, the upscale refine
    upscale model         LatentUpscaleModelLoader
    output                VHS_VideoCombine

The two-pass structure is what makes this expensive: LTX renders at the base
size, upsamples the latent 2x, then refines. At 1920x1080 the base pass measured
141 s/step here and the refine never completed. Halving the base dimensions
quarters the sampling cost and gives the upscaler a much smaller latent.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools._comfyui.vrgdg import VRGDGClient  # noqa: E402

VRGDG_OUTPUT = Path(r"C:\Users\Barrul\AppData\Local\Comfy-Desktop\ComfyUI-Shared\output")


def describe_knobs(graph: dict) -> list[str]:
    """The handful of nodes worth editing, found by class rather than by id."""
    notes: list[str] = []
    # A PrimitiveInt holding a plausible pixel dimension is a knob; one holding a
    # 15-digit number is a seed and editing it by hand is not what anyone wants.
    prims = [(nid, n["inputs"]["value"]) for nid, n in graph.items()
             if n["class_type"] == "PrimitiveInt" and isinstance(n["inputs"].get("value"), int)]
    for nid, val in sorted(prims, key=lambda kv: -kv[1]):
        if 64 <= val <= 8192:
            notes.append(f"  size/frames  {nid:>10}  = {val}")
    for nid, val in prims:
        if val > 100000:
            notes.append(f"  seed         {nid:>10}  = {val}")
    for nid, n in graph.items():
        ct = n["class_type"]
        ins = n.get("inputs", {})
        if ct == "ManualSigmas":
            sig = str(ins.get("sigmas", ""))
            steps = max(0, len([x for x in sig.split(",") if x.strip()]) - 1)
            notes.append(f"  ManualSigmas {nid:>10}  {steps} steps   {sig[:60]}")
        elif ct == "LatentUpscaleModelLoader":
            notes.append(f"  upscaler     {nid:>10}  {ins.get('model_name')}")
        elif ct == "UnetLoaderGGUF":
            notes.append(f"  unet         {nid:>10}  {ins.get('unet_name')}")
        elif ct == "VHS_VideoCombine":
            notes.append(f"  output       {nid:>10}  {ins.get('format')} crf={ins.get('crf')}")
    return notes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", required=True)
    parser.add_argument("--scene", type=int, required=True, help="1-based scene number.")
    parser.add_argument("--images", default=None, help="Folder the scene image is read from.")
    parser.add_argument("--width", type=int, default=None, help="Override the render width.")
    parser.add_argument("--height", type=int, default=None)
    parser.add_argument("--no-upscale", action="store_true",
                        help="Drop the second pass: fewer sigmas, no latent upsample.")
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    project = VRGDG_OUTPUT / args.project
    session = json.loads((project / "vrgdg_builder_session.json").read_text(encoding="utf-8"))
    segments = session.get("segments", [])
    if not 1 <= args.scene <= len(segments):
        print(f"FAIL: scene must be 1..{len(segments)}")
        return 1
    seg = segments[args.scene - 1]

    srt = project / "scene_srt" / f"scene_{args.scene:04d}.srt"
    if not srt.is_file():
        print(f"FAIL: no SRT for this scene at {srt}")
        return 1

    client = VRGDGClient()
    if not client.is_available():
        print("FAIL:", client.unavailable_reason())
        return 1
    defaults = requests.get(
        f"{client.server_url}/vrgdg/music_builder/model_defaults", timeout=30
    ).json()
    cfg = dict((defaults.get("defaults") or defaults)["i2v_video_settings"])
    if args.width:
        cfg["width"] = args.width
    if args.height:
        cfg["height"] = args.height
    if args.no_upscale:
        # One sigma schedule instead of two. The upsample node stays in the graph
        # but the refine pass has nothing to do, which is the cheap way to test
        # whether the second pass is what is hanging.
        cfg["pass2_sigmas"] = "0.0"

    images = Path(args.images) if args.images else project / "openmontage_recast"
    payload = {
        **cfg,
        "i2v_prompt": seg.get("i2v_prompt") or seg.get("t2i_prompt", ""),
        "project_folder": str(project),
        "audio_path": session.get("audio_path", ""),
        "srt_path": str(srt),
        "image_folder": str(images),
    }
    graph = client.build("i2v", payload)
    # VRGDG templates hang RAMCleanup/VRAMCleanup off the graph feeding nothing.
    # Those node types are not installed here, and ComfyUI validates the WHOLE
    # submitted prompt - so a dead branch blocks the render (DECISIONS #5).
    # Pruning to the output node removes them and anything else unreachable.
    output_node = graph.output_node()
    removed = graph.prune(output_node)
    prompt = graph.prompt
    if removed:
        print(f"pruned {len(removed)} unreachable node(s): "
              + ", ".join(sorted({prompt.get(r, {}).get('class_type', r) for r in removed} 
                                 if False else {r for r in removed}))[:120])
    still_missing = client.missing_node_types(prompt)
    if still_missing:
        print("WARNING: node types not installed on this server:", still_missing)

    empty = [
        (nid, n["class_type"], k)
        for nid, n in prompt.items()
        for k, v in n.get("inputs", {}).items()
        if isinstance(v, str) and not v and ("name" in k or "model" in k)
    ]
    if empty:
        print("WARNING: loaders with no model name - the render will fail:")
        for nid, ct, k in empty:
            print(f"    node {nid} {ct}.{k}")

    out = Path(args.out) if args.out else ROOT / "projects" / "burningman" / f"i2v_scene{args.scene:02d}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(prompt, indent=2), encoding="utf-8")

    print(f"{len(prompt)} nodes, output node {output_node}")
    print(f"render size: {cfg['width']}x{cfg['height']} @ {cfg.get('fps')} fps"
          + ("  (second pass disabled)" if args.no_upscale else ""))
    print(f"\nsaved: {out}")
    print("\nOpen it in ComfyUI: Workflow > Open, or drag the file onto the canvas.")
    print("\nnodes worth editing:")
    for line in describe_knobs(prompt):
        print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
